[package]
name = "sudoku"
version = "0.1.0"
authors = ["Mathias Lengler <mathmatze@googlemail.com>"]
edition = "2018"

[dependencies]
itertools = "0.8.0"
rand = "0.6.5"
rayon = "1.0.3"
failure = "0.1.5"
crossterm = "0.8.2"
lazy_static = "1.3.0"
