[workspace]

members = [
    "sudoku-rs",
    "sudoku-wasm",
    "sudoku-afl"
]

[profile.release]
debug = true

[patch.crates-io]
gcollections = { git = "https://github.com/MathiasLengler/gcollections" }
intervallum = { git = "https://github.com/MathiasLengler/intervallum" }
pcp = { git = "https://github.com/MathiasLengler/pcp" }
