[workspace]

members = [
    "sudoku-rs",
    "sudoku-wasm"
]

[profile.release]
debug = true

[patch.crates-io]
gcollections = { path = "../gcollections" }
intervallum = { path = "../intervallum" }
pcp = { path = "../pcp" }
