[package]
name = "sudoku"
version = "0.1.0"
authors = ["Mathias Lengler <mathias@lengler.dev>"]
edition = "2018"

[dependencies]
itertools = "0.8.0"
rand = "0.6.5"
rayon = {version = "1.0.3", optional = true}
failure = "0.1.5"
crossterm = {version = "0.8.2", optional = true}
lazy_static = "1.3.0"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
debug = true

[features]
default = []
debug_print = ["crossterm"]
parallel = ["rayon"]
