// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Candidates } from "./Candidates";
import type { Value } from "./Value";

export type Action = ActionSetValue | ActionDeleteCandidate | ActionDeleteCandidates;
export type ActionSetValue = { setValue: Value };
export type ActionDeleteCandidate = { deleteCandidate: Value };
export type ActionDeleteCandidates = { deleteCandidates: Candidates };