// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CellWorldDimensions = { gridDim: import('../../sudoku-web/src/app/state/world').WorldGridDim, cellDim: import('../../sudoku-web/src/app/state/world').WorldCellDim, overlap: number, };
