// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileDim } from "./TileDim";

export interface CellWorldDimensions { tileDim: TileDim, cellDim: TileDim, overlap: number, }