// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorldDim } from "./WorldDim";

export interface CellWorldDimensions { gridDim: WorldDim, cellDim: WorldDim, overlap: number, }