// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CellView = CellViewValue | CellViewCandidates;
export type CellViewValue = { kind: "value", value: number, fixed: boolean, };
export type CellViewCandidates = { kind: "candidates", candidates: Array<number>, };