// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicPruningSettings } from "./DynamicPruningSettings";
import type { DynamicSolutionSettings } from "./DynamicSolutionSettings";

export interface DynamicGeneratorSettings { base: number, prune?: DynamicPruningSettings, solution?: DynamicSolutionSettings, seed?: bigint, }