// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicGrid } from "./DynamicGrid";

export interface DynamicSolutionSettings {
  valuesGrid: DynamicGrid;
}
