// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicStrategy } from "./DynamicStrategy";
import type { TransportDeductions } from "./TransportDeductions";

export type DynamicTryStrategiesReturn = [DynamicStrategy, TransportDeductions] | null;