// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicCandidates } from "./DynamicCandidates";
import type { DynamicValue } from "./DynamicValue";

export type DynamicCell = DynamicCellValue | DynamicCellCandidates;
export type DynamicCellValue = { "kind": "value", value: DynamicValue, fixed: boolean, };
export type DynamicCellCandidates = { "kind": "candidates", candidates: DynamicCandidates, };