// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DynamicGridFormat = DynamicGridFormatGivensLine | DynamicGridFormatGivensGrid | DynamicGridFormatBinaryCandidatesLine | DynamicGridFormatBinaryFixedCandidatesLine | DynamicGridFormatCandidatesGridColored | DynamicGridFormatCandidatesGridPlain | DynamicGridFormatAsciiCandidatesGrid;
export type DynamicGridFormatGivensLine = "GivensLine";
export type DynamicGridFormatGivensGrid = "GivensGrid";
export type DynamicGridFormatBinaryCandidatesLine = "BinaryCandidatesLine";
export type DynamicGridFormatBinaryFixedCandidatesLine = "BinaryFixedCandidatesLine";
export type DynamicGridFormatCandidatesGridColored = "CandidatesGridColored";
export type DynamicGridFormatCandidatesGridPlain = "CandidatesGridPlain";
export type DynamicGridFormatAsciiCandidatesGrid = "AsciiCandidatesGrid";