// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicGeneratorSettings } from "./DynamicGeneratorSettings";
import type { GoalOptimization } from "./GoalOptimization";
import type { GridMetric } from "./GridMetric";

export type DynamicMultiShotGeneratorSettings = { generatorSettings: DynamicGeneratorSettings, iterations: number, metric: GridMetric, optimize: GoalOptimization, parallel: boolean, };
