// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseEnum } from "./BaseEnum";
import type { DynamicPruningSettings } from "./DynamicPruningSettings";
import type { DynamicSolutionSettings } from "./DynamicSolutionSettings";

export type DynamicGeneratorSettings = { base: BaseEnum, prune?: DynamicPruningSettings | null, solution?: DynamicSolutionSettings | null, seed?: bigint | null, };
