// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicPruningOrder } from "./DynamicPruningOrder";
import type { PruningTarget } from "./PruningTarget";
import type { StrategyEnum } from "./StrategyEnum";

export interface DynamicPruningSettings { setAllDirectCandidates: boolean, strategies: Array<StrategyEnum>, target: PruningTarget, order: DynamicPruningOrder, startFromNearMinimalGrid: boolean, }