// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicPosition } from "./DynamicPosition";
import type { WorldPosition } from "./WorldPosition";

export type DynamicWorldGridCellPosition = { world_grid_pos: WorldPosition, cell_pos: DynamicPosition, };