// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicPruningOrder } from "./DynamicPruningOrder";
import type { DynamicStrategy } from "./DynamicStrategy";
import type { PruningTarget } from "./PruningTarget";

export interface DynamicPruningSettings { setAllDirectCandidates: boolean, strategies: Array<DynamicStrategy>, target: PruningTarget, order: DynamicPruningOrder, startFromNearMinimalGrid: boolean, }