// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicCell } from "./DynamicCell";
import type { DynamicGrid } from "./DynamicGrid";

export type DynamicSolutionSettings = { valuesGrid: DynamicGrid<DynamicCell>, };
