// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StrategyEnum } from "./StrategyEnum";
import type { TransportDeductions } from "./TransportDeductions";

export type DynamicSolveStep = { strategy: StrategyEnum, deductions: TransportDeductions, };
