// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DynamicStrategy = DynamicStrategyNakedSingles | DynamicStrategyHiddenSingles | DynamicStrategyNakedPairs | DynamicStrategyGroupReduction | DynamicStrategyBacktracking;
export type DynamicStrategyNakedSingles = "NakedSingles";
export type DynamicStrategyHiddenSingles = "HiddenSingles";
export type DynamicStrategyNakedPairs = "NakedPairs";
export type DynamicStrategyGroupReduction = "GroupReduction";
export type DynamicStrategyBacktracking = "Backtracking";