// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicPruningOrder } from "./DynamicPruningOrder";
import type { PruningTarget } from "./PruningTarget";
import type { StrategyMap } from "./StrategyMap";

export type DynamicPruningSettings = { setAllDirectCandidates: boolean, strategies: StrategyMap<boolean>, target: PruningTarget, order: DynamicPruningOrder, startFromNearMinimalGrid: boolean, };
