// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DynamicGridFormat = DynamicGridFormatBinaryCandidatesLine | DynamicGridFormatBinaryFixedCandidatesLine | DynamicGridFormatCandidatesGridANSIStyled | DynamicGridFormatCandidatesGridPlain | DynamicGridFormatCandidatesGridCompact | DynamicGridFormatGivensLine | DynamicGridFormatGivensGrid;
export type DynamicGridFormatBinaryCandidatesLine = "BinaryCandidatesLine";
export type DynamicGridFormatBinaryFixedCandidatesLine = "BinaryFixedCandidatesLine";
export type DynamicGridFormatCandidatesGridANSIStyled = "CandidatesGridANSIStyled";
export type DynamicGridFormatCandidatesGridPlain = "CandidatesGridPlain";
export type DynamicGridFormatCandidatesGridCompact = "CandidatesGridCompact";
export type DynamicGridFormatGivensLine = "GivensLine";
export type DynamicGridFormatGivensGrid = "GivensGrid";