// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicCell } from "./DynamicCell";

export interface DynamicGrid<T = DynamicCell> { cells: Array<T>, }