// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicPosition } from "./DynamicPosition";

export type DynamicWorldGridCellPosition = { world_grid_pos: import('../../sudoku-web/src/app/state/world').WorldGridPosition, cell_pos: DynamicPosition, };