// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The position of a cell in a grid of unknown size.
 */
export type DynamicPosition = { row: number, column: number, };
