// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicPosition } from "./DynamicPosition";
import type { PruningGroupBehaviour } from "./PruningGroupBehaviour";

export type DynamicPruningOrder = "random" | { "positions": { positions: Array<DynamicPosition>, behaviour: PruningGroupBehaviour, } } | { "solutionUnfixedValues": { behaviour: PruningGroupBehaviour, } };
