// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DynamicStrategy = DynamicStrategySingleCandidate | DynamicStrategyHiddenSingles | DynamicStrategyGroupReduction | DynamicStrategyBacktracking;
export type DynamicStrategySingleCandidate = "SingleCandidate";
export type DynamicStrategyHiddenSingles = "HiddenSingles";
export type DynamicStrategyGroupReduction = "GroupReduction";
export type DynamicStrategyBacktracking = "Backtracking";