// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratorSettings } from "./GeneratorSettings";

export type DynamicGeneratorSettings = { base: number, } & GeneratorSettings;