// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratorTarget } from "./GeneratorTarget";

export interface GeneratorSettings { base: number, target: GeneratorTarget, }