// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneratorTarget = "filled" | { fromFilled: { distance: number, set_all_direct_candidates: boolean, } } | { minimal: { set_all_direct_candidates: boolean, } } | { fromMinimal: { distance: number, set_all_direct_candidates: boolean, } };