// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneratorTarget = GeneratorTargetFilled | GeneratorTargetFromFilled | GeneratorTargetMinimal | GeneratorTargetFromMinimal;
export type GeneratorTargetFilled = "filled";
export type GeneratorTargetFromFilled = { fromFilled: { distance: number, set_all_direct_candidates: boolean, } };
export type GeneratorTargetMinimal = { minimal: { set_all_direct_candidates: boolean, } };
export type GeneratorTargetFromMinimal = { fromMinimal: { distance: number, set_all_direct_candidates: boolean, } };