// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A metric used to evaluate the difficulty of a grid.
 */
export type GridMetric = "strategyScore" | "strategyApplicationCount" | "strategyDeductionCount" | "strategyAverageOptions" | "solveGraphAverageBranchingFactor" | "satStepCount" | "backtrackingStepCount" | "gridGivensCount" | "gridDirectCandidatesCount" | "gridGivensValueCountDeviation";
