// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GridFormatEnum = "BinaryCandidatesLine" | "BinaryFixedCandidatesLine" | "CandidatesGridANSIStyled" | "CandidatesGridPlain" | "CandidatesGridCompact" | "ValuesLine" | "ValuesGrid";
