// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GridFormatEnum = "BinaryCandidatesLineV0" | "BinaryCandidatesLineV1" | "BinaryCandidatesLineV2" | "CandidatesGridANSIStyled" | "CandidatesGridCompact" | "CandidatesGridPlain" | "Json" | "ValuesGrid" | "ValuesLine";
