// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GridFormatEnum = GridFormatEnumBinaryCandidatesLine | GridFormatEnumBinaryFixedCandidatesLine | GridFormatEnumCandidatesGridANSIStyled | GridFormatEnumCandidatesGridPlain | GridFormatEnumCandidatesGridCompact | GridFormatEnumGivensLine | GridFormatEnumGivensGrid;
export type GridFormatEnumBinaryCandidatesLine = "BinaryCandidatesLine";
export type GridFormatEnumBinaryFixedCandidatesLine = "BinaryFixedCandidatesLine";
export type GridFormatEnumCandidatesGridANSIStyled = "CandidatesGridANSIStyled";
export type GridFormatEnumCandidatesGridPlain = "CandidatesGridPlain";
export type GridFormatEnumCandidatesGridCompact = "CandidatesGridCompact";
export type GridFormatEnumGivensLine = "GivensLine";
export type GridFormatEnumGivensGrid = "GivensGrid";