// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GridFormat = GridFormatGivensLine | GridFormatGivensGrid | GridFormatBinaryCandidatesLine | GridFormatCandidatesGrid;
export type GridFormatGivensLine = "givensLine";
export type GridFormatGivensGrid = "givensGrid";
export type GridFormatBinaryCandidatesLine = "binaryCandidatesLine";
export type GridFormatCandidatesGrid = "candidatesGrid";