// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StrategyEnum } from "./StrategyEnum";

/**
 * A metric used to evaluate the difficulty of a grid.
 */
export type GridMetric = { "kind": "strategyScore" } | { "kind": "strategyApplicationCountAny" } | { "kind": "strategyApplicationCountSingle", strategy: StrategyEnum, } | { "kind": "strategyDeductionCountAny" } | { "kind": "strategyDeductionCountSingle", strategy: StrategyEnum, } | { "kind": "strategyAverageOptions" } | { "kind": "solveGraphAverageBranchingFactor" } | { "kind": "satStepCount" } | { "kind": "backtrackCount" } | { "kind": "gridGivensCount" } | { "kind": "gridDirectCandidatesCount" } | { "kind": "gridGivensValueCountDeviation" };
