// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MultiShotGeneratorProgress = { "kind": "started", currentIteration: number, totalIterations: number, } | { "kind": "finished", currentIteration: number, totalIterations: number, currentEvaluatedGridMetric: bigint, bestEvaluatedGridMetric: bigint, };
