// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicCandidates } from "./DynamicCandidates";
import type { DynamicPosition } from "./DynamicPosition";
import type { DynamicValue } from "./DynamicValue";

export type PositionedTransportAction = { position: DynamicPosition, } & ({ "setValue": DynamicValue } | { "deleteCandidates": DynamicCandidates });
