// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PruningTarget = PruningTargetMinimal | PruningTargetMinimalPlusClueCunt | PruningTargetMaxEmptyCellCount | PruningTargetMinClueCount;
export type PruningTargetMinimal = "minimal";
export type PruningTargetMinimalPlusClueCunt = { "minimalPlusClueCunt": number };
export type PruningTargetMaxEmptyCellCount = { "maxEmptyCellCount": number };
export type PruningTargetMinClueCount = { "minClueCount": number };