// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Candidates } from "./Candidates";
import type { Value } from "./Value";

export type Reason = ReasonCandidate | ReasonCandidates;
export type ReasonCandidate = { candidate: { candidate: Value, } };
export type ReasonCandidates = { candidates: { candidates: Candidates, } };