// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Candidates } from "./Candidates";

export type Reason = ReasonCandidates;
export type ReasonCandidates = { candidates: Candidates };