// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RelativeTileDir = RelativeTileDirTopLeft | RelativeTileDirTop | RelativeTileDirTopRight | RelativeTileDirLeft | RelativeTileDirRight | RelativeTileDirBottomLeft | RelativeTileDirBottom | RelativeTileDirBottomRight;
export type RelativeTileDirTopLeft = "topLeft";
export type RelativeTileDirTop = "top";
export type RelativeTileDirTopRight = "topRight";
export type RelativeTileDirLeft = "left";
export type RelativeTileDirRight = "right";
export type RelativeTileDirBottomLeft = "bottomLeft";
export type RelativeTileDirBottom = "bottom";
export type RelativeTileDirBottomRight = "bottomRight";