// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RelativeGridDir = RelativeGridDirTopLeft | RelativeGridDirTop | RelativeGridDirTopRight | RelativeGridDirLeft | RelativeGridDirRight | RelativeGridDirBottomLeft | RelativeGridDirBottom | RelativeGridDirBottomRight;
export type RelativeGridDirTopLeft = "topLeft";
export type RelativeGridDirTop = "top";
export type RelativeGridDirTopRight = "topRight";
export type RelativeGridDirLeft = "left";
export type RelativeGridDirRight = "right";
export type RelativeGridDirBottomLeft = "bottomLeft";
export type RelativeGridDirBottom = "bottom";
export type RelativeGridDirBottomRight = "bottomRight";