// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A map of `StrategyEnum` to `T`.
 */
export type StrategyMap<T> = { naked_singles: T, hidden_singles: T, naked_pairs: T, locked_sets: T, group_intersection_block_to_axis: T, group_intersection_axis_to_block: T, group_intersection_both: T, x_wing: T, w_wing: T, brute_force: T, };
