// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StrategyEnum = StrategyEnumNakedSingles | StrategyEnumHiddenSingles | StrategyEnumNakedPairs | StrategyEnumGroupReduction | StrategyEnumGroupIntersectionBlockToAxis | StrategyEnumGroupIntersectionAxisToBlock | StrategyEnumGroupIntersectionBoth | StrategyEnumBacktracking;
export type StrategyEnumNakedSingles = "NakedSingles";
export type StrategyEnumHiddenSingles = "HiddenSingles";
export type StrategyEnumNakedPairs = "NakedPairs";
export type StrategyEnumGroupReduction = "GroupReduction";
export type StrategyEnumGroupIntersectionBlockToAxis = "GroupIntersectionBlockToAxis";
export type StrategyEnumGroupIntersectionAxisToBlock = "GroupIntersectionAxisToBlock";
export type StrategyEnumGroupIntersectionBoth = "GroupIntersectionBoth";
export type StrategyEnumBacktracking = "Backtracking";