// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tiling pattern that determines which grid positions in a world are active (contain a grid)
 * and which are gaps/holes.
 *
 * Different patterns create different visual layouts and difficulty levels:
 * - Regular: All positions are active (current implementation)
 * - Chainlink: Checkerboard pattern with diagonal overlaps only
 * - Other patterns for fractal-like or hole patterns
 */
export type TilingPattern = "regular" | "chainlink";
