// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellView } from "./CellView";
import type { Position } from "./Position";

export type TransportCell = { position: Position, incorrectValue: boolean, } & CellView;