// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { Position } from "./Position";

export type TransportAction<Base> = { position: Position, } & Action;