// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicCandidates } from "./DynamicCandidates";
import type { DynamicValue } from "./DynamicValue";

export type TransportAction = TransportActionSetValue | TransportActionDeleteCandidates;
export type TransportActionSetValue = { setValue: DynamicValue };
export type TransportActionDeleteCandidates = { deleteCandidates: DynamicCandidates };