// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransportCell } from "./TransportCell";

export interface TransportSudoku { blocks: Array<Array<TransportCell>>, base: number, sideLength: number, cellCount: number, isSolved: boolean, canUndo: boolean, canRedo: boolean, }