// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicPosition } from "./DynamicPosition";
import type { Reason } from "./Reason";

export type TransportReason = { position: DynamicPosition, } & Reason;