// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseEnum } from "./BaseEnum";
import type { TransportCell } from "./TransportCell";
import type { TransportHistory } from "./TransportHistory";
import type { TransportSolutionState } from "./TransportSolutionState";

export type TransportSudoku = { cells: Array<TransportCell>, base: BaseEnum, blocksIndexes: Array<Array<number>>, sideLength: number, cellCount: number, history: TransportHistory, isSolved: boolean, solutionState: TransportSolutionState, };
