// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicCandidates } from "./DynamicCandidates";

export type TransportReason = TransportReasonCandidates;
export type TransportReasonCandidates = { candidates: DynamicCandidates };