// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionedTransportAction } from "./PositionedTransportAction";
import type { PositionedTransportReason } from "./PositionedTransportReason";

export type TransportDeduction = { reasons: Array<PositionedTransportReason>, actions: Array<PositionedTransportAction>, };