// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransportAction } from "./TransportAction";
import type { TransportReason } from "./TransportReason";

export interface TransportDeduction { reasons: Array<TransportReason>, actions: Array<TransportAction>, }