// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransportDeduction } from "./TransportDeduction";

export interface TransportDeductions { deductions: Array<TransportDeduction>, }