// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { Reason } from "./Reason";

export type TransportReason = { position: Position, } & Reason;