// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorldPosition } from "./WorldPosition";

/**
 * A rectangular region of cells defined by a start (top-left, inclusive) and end (bottom-right, exclusive) position.
 */
export type WorldCellRegion = { 
/**
 * Top-left corner (inclusive)
 */
start: WorldPosition, 
/**
 * Bottom-right corner (exclusive)
 */
end: WorldPosition, };
