// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A position of a `WorldObject`.
 */
export type WorldPosition = { row: number, column: number, };
