[package]
name = "sudoku"
version = "0.1.0"
authors = ["Mathias Lengler <mathias@lengler.dev>"]
edition = "2018"

[dependencies]
itertools = "0.8.0"
rand = "0.6.5"
rayon = { version = "1.0.3", optional = true }
failure = "0.1.5"
crossterm = { version = "0.9.5", optional = true }
lazy_static = "1.3.0"
serde = { version = "1.0.91", features = ["derive"] }
fixedbitset = "0.1.9"
num = "0.2.0"
nonzero_ext = "0.1.5"
log = "0.4.6"

[dev-dependencies]
criterion = "0.2.11"

[[bench]]
name = "sudoku_benchmark"
harness = false
required-features = ["benchmark"]

[features]
default = []
debug_print = ["crossterm"]
parallel = ["rayon"]
wasm-bindgen = ["rand/wasm-bindgen"]
benchmark = []
