[package]
name = "sudoku"
version = "0.1.0"
authors = ["Mathias Lengler <mathias@lengler.dev>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
rand = "0.7.3"
anyhow = "1.0.33"
lazy_static = "1.4.0"
serde = { version = "1.0.114", features = ["derive"] }
fixedbitset = "0.3.0"
bitvec = { version = "0.17.4", default-features = false, features = ["std"] }
num = "0.3.0"
pcp = { git = "https://github.com/MathiasLengler/pcp" }
intervallum = { git = "https://github.com/MathiasLengler/intervallum" }
gcollections = { git = "https://github.com/MathiasLengler/gcollections" }
indexmap = "1.4.0"
ndarray = "0.13.1"
generic-array = "0.14.2"
typenum = "1.12.0"
rayon = { version = "1.3.1", optional = true }
crossterm = { version = "0.17.5", optional = true }
flame = { version = "0.2.2", optional = true }
flamer = { version = "0.4.0", optional = true }
enum_dispatch = "0.3.1"
arbitrary = { version = "0.4.5", features = ["derive"], optional = true }

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "sudoku_benchmark"
harness = false

[features]
default = []
debug_print = ["crossterm"]
parallel = ["rayon"]
wasm-bindgen = ["rand/wasm-bindgen"]
flame_it = ["flame", "flamer"]
fuzz = ["arbitrary"]
