[package]
name = "sudoku"
version = "0.1.0"
authors = ["Mathias Lengler <mathias@lengler.dev>"]
edition = "2018"

[dependencies]
itertools = "0.10.0"
rand = "0.8.3"
getrandom = "0.2.2"
anyhow = "1.0.38"
lazy_static = "1.4.0"
serde = { version = "1.0.124", features = ["derive"] }
fixedbitset = "0.3.2"
bitvec = { version = "0.21.1", default-features = false, features = ["std"] }
num = "0.4.0"
pcp = { git = "https://github.com/MathiasLengler/pcp" }
intervallum = { git = "https://github.com/MathiasLengler/intervallum" }
gcollections = { git = "https://github.com/MathiasLengler/gcollections" }
indexmap = "1.6.2"
ndarray = "0.14.0"
generic-array = "0.14.4"
typenum = "1.12.0"
rayon = { version = "1.5.0", optional = true }
crossterm = { version = "0.19.0", optional = true }
flame = { version = "0.2.2", optional = true }
flamer = { version = "0.4.0", optional = true }
enum_dispatch = "0.3.6"
arbitrary = { version = "1.0.0", features = ["derive"], optional = true }

[dev-dependencies]
criterion = "0.3.4"

[[bench]]
name = "sudoku_benchmark"
harness = false

[features]
default = []
debug_print = ["crossterm"]
parallel = ["rayon"]
wasm-bindgen = ["getrandom/js"]
flame_it = ["flame", "flamer"]
fuzz = ["arbitrary"]
