[package]
name = "sudoku"
version = "0.1.0"
authors = ["Mathias Lengler <mathias@lengler.dev>"]
edition = "2018"

[dependencies]
itertools = "0.8.0"
rand = "0.7.2"
rayon = { version = "1.2.0", optional = true }
failure = "0.1.5"
crossterm = { version = "0.11.1", optional = true }
lazy_static = "1.4.0"
serde = { version = "1.0.101", features = ["derive"] }
fixedbitset = "0.1.9"
num = "0.2.0"
nonzero_ext = "0.1.5"
log = "0.4.8"
pcp = "0.6.1"
intervallum = "1.3.0"
gcollections = "1.4.0"
indexmap = "1.2.0"

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "sudoku_benchmark"
harness = false

[features]
default = []
debug_print = ["crossterm"]
parallel = ["rayon"]
wasm-bindgen = ["rand/wasm-bindgen"]
