[package]
name = "sudoku"
version = "0.1.0"
authors = ["Mathias Lengler <mathias@lengler.dev>"]
edition = "2018"

[dependencies]
itertools = "0.8.2"
rand = "0.7.3"
failure = "0.1.6"
lazy_static = "1.4.0"
serde = { version = "1.0.104", features = ["derive"] }
fixedbitset = "0.2.0"
fixed-bitset = "0.0.1"
bitvec = { version = "0.17.1", default-features = false, features = ["std"] }
num = "0.2.1"
nonzero_ext = "0.2.0"
log = "0.4.8"
pcp = { git = "https://github.com/MathiasLengler/pcp" }
intervallum = { git = "https://github.com/MathiasLengler/intervallum" }
gcollections = { git = "https://github.com/MathiasLengler/gcollections" }
indexmap = "1.3.1"
ndarray = "0.13.0"
generic-array = "0.13.2"
typenum = "1.11.2"
rayon = { version = "1.3.0", optional = true }
crossterm = { version = "0.14.2", optional = true }
flame = { version = "0.2.2", optional = true }
flamer = { version = "0.4.0", optional = true }
static_assertions = "1.1.0"
enum_dispatch = "0.2.0"

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "sudoku_benchmark"
harness = false

[features]
default = []
debug_print = ["crossterm"]
parallel = ["rayon"]
wasm-bindgen = ["rand/wasm-bindgen"]
flame_it = ["flame", "flamer"]
