name: Deploy

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Rust
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      # Node
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'sudoku-web/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'sudoku-web/package-lock.json'

      - run: npm ci
        working-directory: ./sudoku-web

      - run: npm run lint
        working-directory: ./sudoku-web

      # https://webpack.js.org/configuration/cache/#github-actions
      - uses: actions/cache@v3
        with:
          # cache directory
          path: sudoku-web/node_modules/.cache/webpack/
          key: ${{ GITHUB_REF_NAME }}-webpack-build
          # fallback to use "main" branch cache
          restore-keys: |
            main-webpack-build

      - run: npm run build
        working-directory: ./sudoku-web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sudoku-web/dist

      - name: Deploy to Cloudflare Pages
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.CLOUDFLARE_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.CLOUDFLARE_WEBHOOK_SECRET }}
