name: Deploy

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3

      # Rust
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      # Node
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'sudoku-web/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'sudoku-web/package-lock.json'

      - run: npm ci
        working-directory: ./sudoku-web

      - run: npm run lint
        working-directory: ./sudoku-web

      - run: npm run build
        working-directory: ./sudoku-web

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: sudoku
          directory: sudoku-web/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
