name: Deploy

on:
  push:
    branches:
      - "master"
      - "test"
  workflow_dispatch:

env:
  CI: true
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      # Rust
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-11-15
          targets: wasm32-unknown-unknown
          components: clippy, rust-src

      # just
      - uses: extractions/setup-just@v3

      # cargo nextest
      - uses: taiki-e/install-action@nextest

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: clippy
        run: just clippy-ci

      - name: test
        run: just test

      - name: wasm-pack
        run: just pack-prod

      # Node
      - uses: actions/setup-node@v4
        with:
          node-version-file: "sudoku-web/.nvmrc"
          cache: "npm"
          cache-dependency-path: "sudoku-web/package-lock.json"

      - run: npm ci
        working-directory: ./sudoku-web

      - run: npm run lint
        working-directory: ./sudoku-web

      - run: npm run build
        working-directory: ./sudoku-web

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker-registry.lengler.dev/sudoku
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # add tag based on branch name
            type=ref,event=branch

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker-registry.lengler.dev
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./sudoku-web
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy to Coolify
        run: |
          curl --fail-with-body --request GET '${{ github.ref == 'refs/heads/master' && secrets.COOLIFY_WEBHOOK_PROD || secrets.COOLIFY_WEBHOOK_TEST }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
