[package]
authors = ["Mathias Lengler <mathias@lengler.dev>"]
name = "sudoku-wasm"
readme = "./README.md"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
# wasm
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
console_log = { version = "0.2.0", optional = true }
js-sys = "0.3.47"

# own
log = "0.4.11"
sudoku = { path = "../sudoku-rs", features= ["wasm-bindgen"]}
serde = "1.0.118"

# wasm
[dependencies.web-sys]
version = "0.3.46"
features = [
  "Document",
  "Element",
  "HtmlElement",
  "Node",
  "Window",
]

[dependencies.wasm-bindgen]
version = "0.2.69"
features = ["serde-serialize"]

[features]
default = ["console"]
console = ["console_error_panic_hook", "console_log"]
